# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "github-actions" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: build TeXLive 2022
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install perl
          mkdir downloads 
          cd downloads 
          pwd
          wget https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz 
          zcat install-tl-unx.tar.gz | tar xf - 
          cd install-tl-???????? 
          sudo perl ./install-tl --scheme=small --no-interaction 
          sudo /usr/local/texlive/????/bin/x86_64-linux/tlmgr install collection-langcjk collection-langjapanese
          cd 
          platex test.tex
          dvipdfmx test.dvi
          

